(require 'package)
(dolist (source '(("marmalade" . "http://marmalade-repo.org/packages/")
                  ("elpa" . "http://tromey.com/elpa/")
                  ("melpa" . "http://melpa.milkbox.net/packages/")
                  ))
  (add-to-list 'package-archives source t))
(package-initialize)

(add-to-list 'load-path "~/.emacs.d/libs")
(add-to-list 'load-path "~/.emacs.d/config")
(load-theme 'monokai t)
(setq-default tab-width 2)
(require 'autopair)
(autopair-global-mode 1)
(setq autopair-autowrap t)
(require 'yasnippet)
(yas-global-mode 1)
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories "~/.emacs.d/ac-dict")
(ac-config-default)
(ac-set-trigger-key "TAB")
(ac-set-trigger-key "<tab>")
(custom-set-variables
 '(initial-frame-alist (quote ((fullscreen . maximized)))))
(setq ido-decorations
'("\n=> " "" "\n" "" "[" "]" " [No match]" " [Matched]" " [Not readable]" " [Too big]" " [Confirm]"))
;;; modify the interface of dired output
(require 'dired-details+)
(setq dired-details-hide-link-targets nil)
;;; set the number of collumns to go to next line
(setq-default fill-column 80)
;;; moz
;;;(add-to-list 'load-path "~/.emacs.d/")
(autoload 'moz-minor-mode "moz" "Mozilla Minor and Inferior Mozilla Modes" t)
(add-hook 'javascript-mode-hook 'javascript-custom-setup)
(defun javascript-custom-setup ()
  (moz-minor-mode 1))
(require 'sudo-save)
;;;Hooking up with Projectile
(projectile-global-mode)
(add-hook 'projectile-mode-hook 'projectile-rails-on)
;;;Delete selection mode turn on globally
(delete-selection-mode)


(require 'linh-yas-ac)
(require 'linh-dired)
(require 'linh-web-mode)
(require 'linh-simple-secret)
(require 'linh-js3-mode)
(require 'linh-nyan-cat-mode)
(require 'linh-eshell-mode)
(require 'linh-ror-mode)
(require 'linh-buffer)
(require 'linh-keymap)
(require 'linh-org-mode)
(require 'linh-sqli)
(require 'linh-tramp)
(require 'linh-hideshow)
(require 'linh-indentation)
(require 'linh-moz-repl)
(require 'linh-javascript-mode)
(require 'linh-golden-ratio)
